### ISSUE TITLE
Remove `Copy` Bound from `NodeId`

### ISSUE THREAD

**Issue by drmingdrmer** [databendlabs/openraft#1250]
# Remove `Copy` Bound from `NodeId`

## Current Situation

The `NodeId` type is currently defined in [src/node.rs](https://github.com/databendlabs/openraft/blob/5d75cf21f71b083b2b8acd8ffdd8993c1bfce36f/openraft/src/node.rs) as:

```rust
type NodeId: .. + Copy + .. + 'static;
```

This definition restricts applications from using non-`Copy` types such as `String` as `NodeId`.

## Proposed Change

We propose removing the `Copy` bound from `NodeId`. This modification will allow the use of non-`Copy` types as `NodeId`, providing greater flexibility for applications that prefer variable-length strings or other non-`Copy` types for node identification.

These change should maintain compatibility and must not break applications.

## Implementation Details

To implement this change, we need to:

1. Replace all copy operations with explicit `.clone()` calls.
2. Update derived `Copy` implementations with manual implementations where necessary, in order to maintain compatibility. For example:
   ```rust
   // Before
   #[derive(Copy...)]
   pub struct LogId<NID: NodeId> {}
   
   // After
   impl<NID: Copy> Copy for LogId<NID> {}
   ```

## Performance Considerations

Our analysis suggests that the performance impact of this change will be negligible for simple objects that don't involve heap allocation. Benchmarks comparing `Clone` and `Copy` for non-heap-allocated objects show nearly identical performance:

[Benchmark Results](https://github.com/drmingdrmer/bench-copy-clone)

This means:
- Existing applications using `Copy` types for `NodeId` should see no significant performance changes.
- New applications using non-`Copy` types for `NodeId` may experience a slight performance difference, but it should be minimal in most cases.

## Benefits

This change will:
1. Increase flexibility for `NodeId` type selection in applications.
2. Allow the use of more complex or variable-length identifiers when needed.
3. Maintain performance for existing use cases while opening up new possibilities.

We believe this modification will enhance Openraft's versatility without compromising its current functionality or performance.

**Comment by SteveLauC** [comment]
I second this!

Actually, I was indeed surprised that the `NodeId` needs to be `Copy` when accessing Openraft for the first time.

> New applications using non-Copy types for NodeId may experience a slight performance difference, but it should be minimal in most cases.

Perhaps we could document the impact of the `.clone()` within Openraft, something like:

> Be aware that `NodeId` will be `.clone()`d within Openraft so that heap-allocated `NodeId` could lead to slightly bad performance.
