### ISSUE TITLE
Make `loosen-follower-log-revert` a runtime functionality instead of a feature

### ISSUE THREAD

**Issue by schreter** [databendlabs/openraft#1251]
Currently, we have a feature called `loosen-follower-log-revert` to allow follower's log to be cut. This is normally undesirable, since it shows a problem in the follower implementation and should not be used.

However, there are use cases when a node is being recovered in failure case and the log is (partially) reinitialized. This is orchestrated from the outside. In this case, it might be desirable to temporarily allow follower's log to go back.

There are currently a few options how to do this that I can think of:
- Create a completely new node with a new node ID and add it to the consensus, then remove the old node. This would work, but it is cumbersome and won't allow easily recovering of a node in-place.
- Allow log revert in general, which is undesirable, since it covers up potential real problems.
- Add a functionality to explicitly reset the match index of a particular follower to a specific value to tell the leader that the follower was recovered from a backup and the like.

Opinions? Am I missing something?

**Comment by drmingdrmer** [comment]
The third approach seems feasible to me. This is also a scenario I've encountered, unfortunately :(
