### ISSUE TITLE
Allow overriding `LogIdList::load_log_ids` by providing the information directly from the state machine or log reader

### ISSUE THREAD

**Issue by schreter** [databendlabs/openraft#1261]
Currently, when `openraft` starts, it scans the entire log with random accesses to find key log IDs where the leader changed. However, this information may be already available in other state machine metadata (as it is in our case), so it can be provided to `openraft` by the state machine implementation, greatly reducing the effort finding key log IDs.

My suggestion is to add a trait method to provide key log IDs and default-implement it with the current search algorithm. If the implementation of the state machine has a better way to provide key log IDs, then it can override the method and provide them directly.

**Comment by drmingdrmer** [comment]
Why is such key-log-id metadata stored in state machine? shouldn't be part of the Raft log?

Does your state machine provide the complete key-log-id or just the applied log-ids? If there are some logs that are not in state machine, Openraft still needs several other rounds of RaftLogStorage access to locate these key log ids.

**Comment by schreter** [comment]
> Why is such key-log-id metadata stored in state machine? shouldn't be part of the Raft log?

For us, the state machine includes log storage. So the two `openraft` interfaces are effectively backed by the same implementation. But yes, logically, it's part of the log.

> Does your state machine provide the complete key-log-id or just the applied log-ids?

All log IDs which were logged, also not applied. Key log IDs are part of log segment management (and stored in log segment metadata). So we can quickly reconstruct the entire set of key log IDs (leader changes) from this metadata w/o loading the log proper.

**Comment by drmingdrmer** [comment]
> For us, the state machine includes log storage. So the two `openraft` interfaces are effectively backed by the same implementation. But yes, logically, it's part of the log.

So, it could be another RaftLogStorage API to return all of the key log id.
