### ISSUE TITLE
Demo: Implement protobuf for RPC

### ISSUE THREAD

**Issue by ppamorim** [databendlabs/openraft#161]
Would be nice to have the example using protobuf for the inner communication between nodes. I will implement that in a separated project, if it works I will implement that on the demo, if any interest is present.

**Comment by ppamorim** [comment]
@BohuTANG I could implement something but the implementation is TERRIBLE and I am ashamed to ever write this code.

**Comment by MikaelCall** [comment]
@ppamorim 

The solution that I've seen most often is to use gRPC and tonic. This will be more efficient than using HTTP like the demo is ATM. However, one major benefit of using HTTP in the current demo is that it is very easy to follow (more familiar, no codegen, etc). This is IMHO one of the main benefits with the demo: simplicity. When you want an "advanced demo" more ready for production, look at metasrv in the databend repo. That being said, adding a more efficient RPC mechanism would be nice, but I'd consider having it behind a feature flag and definitely keep the HTTP endpoints for clarity.

**Comment by sainad2222** [comment]
I tried to pick this but I cannot find any efficient way to reuse responses from existing structs(ClientWriteResponse,VoteResponse etc). Any ideas are welcome

**Comment by sainad2222** [comment]
@drmingdrmer We can close this too
